version: '3.7'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5433:5432

  backend_prod:
    container_name: api_prod
    image: backend_prod:1.0.0
    build:
      context: ../../
      target: prod
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    command: npm run start:prod
    network_mode: 'host'
    volumes:
      - /home/node/app/node_modules
    stdin_open: true
    restart: unless-stopped
    ports:
      - 1337:1337
    depends_on:
      - postgres

volumes:
  postgres:
