version: '3.7'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5433:5432

  backend_dev:
    container_name: api_dev
    image: backend_dev
    build:
      context: ../
      target: dev
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:debug
    ports:
      - 1337:1337
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - postgres
    stdin_open: true
    restart: unless-stopped

  backend_prod:
    container_name: api_prod
    image: backend_prod
    build:
      context: ../
      target: prod
      dockerfile: ./docker/Dockerfile
    env_file: .env
    command: npm run start:prod
    ports:
      - 1337:1337
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - postgres
    stdin_open: true
    restart: unless-stopped

volumes:
  postgres:
